language: android
dist: precise
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
env:
  global:
    - _FORCE_LOGS=1
    - DEVICE=android
    - MOCHA_TIMEOUT=640000
    - RECURSIVE=
    - START_EMU=1
    - ANDROID_EMU_NAME=test
    - ANDROID_EMU_TARGET=android-21
    - ANDROID_EMU_ABI=armeabi-v7a
  matrix:
    - START_EMU=0 RECURSIVE=--recursive TEST=unit COVERALLS=1
    - TEST=functional
    - TEST=functional/commands
    - TEST=functional/commands/find
    - TEST=functional/commands/keyboard
    - TEST=functional/commands TESTOBJECT_E2E_TESTS=true
    - TEST=functional/commands/find TESTOBJECT_E2E_TESTS=true
    - TEST=functional/commands/keyboard TESTOBJECT_E2E_TESTS=true
before_script:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install 6
  - node --version
  - npm --version
  - npm install appium-test-support # get the travis emu scripts

  # android stuff
  - if $TESTOBJECT_E2E_TESTS; then android list targets; fi
  - if $TESTOBJECT_E2E_TESTS; then $(npm bin)/android-emu-travis-pre; fi

  - SERVER_INSTALL_ATTEMPTS=50 npm install

  # make sure emulator started
  - if $TESTOBJECT_E2E_TESTS; then $(npm bin)/android-emu-travis-post; fi
script:
<<<<<<< HEAD
  - npm run lint && npm run mocha -- -t $MOCHA_TIMEOUT -R spec $RECURSIVE build/test/$TEST -ig @skip-ci
=======
  - gulp eslint && mocha -t $MOCHA_TIMEOUT -R spec $RECURSIVE build/test/functional/helpers/mocha-scripts.js build/test/$TEST -ig @skip-ci
>>>>>>> Add mocha script that overrides WD to use TestObject
after_success:
  - if [ -n "$COVERALLS" ]; then _FORCE_LOGS=0 npm run coverage; fi
